config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root 'static_pages#top'
  get 'term', to: 'static_pages#term'
  get 'privacy', to: 'static_pages#privacy'
  get '/login', to: 'user_sessions#new', as: :login
  post '/login', to: 'user_sessions#create'
  delete '/logout', to: 'user_sessions#destroy', as: :logout

  resources :hotels do
    collection do
      get 'search'
    end
  end

  resources :users, only: [:new, :create, :show, :edit]
  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/shared/_before_login_header.html.erb
<div class="navbar bg-accent text-white">
  <div class="flex-1">
    <!-- メニュー項目 -->
    <%=link_to 'Top', root_path, class:"btn btn-ghost text-xl"%>
    <div class="group inline-block relative">
      <%=link_to 'Search', hotels_path, class:"btn btn-ghost text-xl"%>
    </div>
  </div>
    <div class="relative group ">
      <button id="menuButton" class="btn btn-square btn-ghost">
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" class="inline-block w-5 h-5 stroke-current">
      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 12h.01M12 12h.01M19 12h.01M6 12a1 1 0 11-2 0 1 1 0 012 0zm7 0a1 1 0 11-2 0 1 1 0 012 0zm7 0a1 1 0 11-2 0 1 1 0 012 0z"></path>
    </svg>
  </button>
  <ul id="menuList" class="absolute hidden text-base-content bg-accent text-white shadow-lg w-48 top-8 right-0 z-50">
    <li><%=link_to '会員登録', new_user_path, class: "block px-4 py-2" %></li>
    <li><%=link_to 'ログイン', login_path, class: "block px-4 py-2"%></li>
        <li><a href="#" class="block px-4 py-2">お問合せ</a></li>
    <!-- もっと多くのメニュー項目を追加できます -->
  </ul>
  </div>


  </div>
</div>

<script>
  document.getElementById('menuButton').addEventListener('click', function() {
  document.getElementById('menuList').classList.toggle('hidden');
});
</script>

app/views/shared/_footer.html.erb
<footer class="footer footer-center p-4 bg-accent text-white rounded">
  <nav class="grid grid-flow-col gap-4 ">
    <%= link_to 'プライバシーポリシー', privacy_path, class: "link link-hover" %>
    <%= link_to '利用規約', term_path, class: "link link-hover" %>
    <!-- Rakuten Web Services Attribution Snippet FROM HERE -->
    <a href="https://webservice.rakuten.co.jp/" target="_blank"><img src="https://webservice.rakuten.co.jp/img/credit/200709/credit_22121.gif" border="0" alt="Rakuten Web Service Center" title="Rakuten Web Service Center" width="221" height="21"/></a>
    <!-- Rakuten Web Services Attribution Snippet TO HERE -->
  </nav> 
</footer>

app/views/shared/_header.html.erb
<div class="navbar bg-accent text-white">
  <div class="flex-1">
    <!-- メニュー項目 -->
    <%=link_to 'Top', root_path, class:"btn btn-ghost text-xl"%>
    <div class="group inline-block relative">
      <%=link_to 'Search', hotels_path, class:"btn btn-ghost text-xl"%>
    </div>
  </div>
    <div class="relative group ">
      <button id="menuButton" class="btn btn-square btn-ghost">
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" class="inline-block w-5 h-5 stroke-current">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 12h.01M12 12h.01M19 12h.01M6 12a1 1 0 11-2 0 1 1 0 012 0zm7 0a1 1 0 11-2 0 1 1 0 012 0zm7 0a1 1 0 11-2 0 1 1 0 012 0z"></path>
        </svg>
      </button>
      <ul id="menuList" class="absolute hidden text-base-content bg-accent text-white shadow-lg w-48 top-8 right-0 z-50">
        <li><%= button_to 'ログアウト', logout_path, method: :delete, class: "block px-4 py-2" %></li>
        <li><%=link_to 'マイページ',user_path(current_user.id), class: "block px-4 py-2" %></li>
        <li><a href="#" class="block px-4 py-2">お問合せ</a></li>
    <!-- もっと多くのメニュー項目を追加できます -->
      </ul>
    </div>


  </div>
</div>

<script>
  document.getElementById('menuButton').addEventListener('click', function() {
  document.getElementById('menuList').classList.toggle('hidden');
});
</script>