config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root 'static_pages#top'
  get 'term', to: 'static_pages#term'
  get 'privacy', to: 'static_pages#privacy'
  get '/login', to: 'user_sessions#new', as: :login
  post '/login', to: 'user_sessions#create'
  delete '/logout', to: 'user_sessions#destroy', as: :logout

  resources :hotels do
    collection do
      get 'search'
    end
  end

  resources :users, only: [:new, :create, :show, :edit]
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/hotel.rb
class Hotel < ApplicationRecord
  has_many :reviews
  has_one :prefecture
  def self.ransackable_attributes(_auth_object = nil)
    %w[created_at id name name_url prefecture_id updated_at]
  end

  def self.ransackable_associations(_auth_object = nil)
    %w[prefecture reviews]
  end
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  require 'uri'
  require 'net/http'
  require 'json'

  def index
    @hotels = Hotel.all
    @prefectures = Prefecture.all
    @q = Hotel.ransack(params[:q])
  end

  def search
    @q = Hotel.ransack(params[:q])
    @results = @q.result(distinct: true)
    reviews_age_eq = params[:q][:reviews_age_eq]
    @reviews = if reviews_age_eq == 'on'
                 Review.joins(:hotel).merge(@results)
               else
                 Review.joins(:hotel).merge(@results).where(age: reviews_age_eq)
               end

    @hotel_apis = []

    @results.each do |hotel|
      encoded_name = URI.encode_www_form_component(hotel.name)

      rakuten_url = "https://app.rakuten.co.jp/services/api/Travel/KeywordHotelSearch/20170426?format=json&searchField=1&hotelThumbnailSize=1&elements=hotelName,address1,address2,hotelImageUrl,roomImageUrl,reviewCount,reviewAverage&formatVersion=2&keyword=#{encoded_name}&applicationId=#{ENV['id']}"
      uri = URI.parse(rakuten_url)
      response = Net::HTTP.get_response(uri)
      detail = JSON.parse(response.body)
      unless detail && detail['hotels'] && detail['hotels'][0] && detail['hotels'][0][0] && detail['hotels'][0][0]['hotelBasicInfo']
        next
      end

      hotel_api = {
        hotel_name: detail['hotels'][0][0]['hotelBasicInfo']['hotelName'],
        address1: detail['hotels'][0][0]['hotelBasicInfo']['address1'],
        address2: detail['hotels'][0][0]['hotelBasicInfo']['address2'],
        hotel_image: detail['hotels'][0][0]['hotelBasicInfo']['hotelImageUrl'],
        room_image: detail['hotels'][0][0]['hotelBasicInfo']['roomImageUrl'],
        review_count: detail['hotels'][0][0]['hotelBasicInfo']['reviewCount'],
        review_average: detail['hotels'][0][0]['hotelBasicInfo']['reviewAverage']
      }
      @hotel_apis << hotel_api
    end
  end

  def show
    @hotel = Hotel.find(params[:id])
    @hotel_api = fetch_hotel_api(@hotel.name)
    @reviews = @hotel.reviews
    hotel_no = fetch_hotel_no(@hotel.name)
    # フォームからのデータを取得
    return unless params[:reservation]

    checkin_date = params[:reservation][:checkin_date] # YYYY-MM-DD形式
    checkout_date = params[:reservation][:checkout_date] # YYYY-MM-DD形式
    adult_num = params[:reservation][:adult_num]
    infant_with_mb = params[:reservation][:infant_with_mb]
    infant_with_m = params[:reservation][:infant_with_m]
    infant_with_b = params[:reservation][:infant_with_b]
    infant_without_mb = params[:reservation][:infant_witout_mb]
    @room_info = check_vacant_rooms(hotel_no, checkin_date, checkout_date, adult_num, infant_with_mb, infant_with_m,
                                    infant_with_b, infant_without_mb)
  end

  private

  def fetch_hotel_api(hotel_name)
    encoded_name = URI.encode_www_form_component(hotel_name)
    rakuten_url = "https://app.rakuten.co.jp/services/api/Travel/KeywordHotelSearch/20170426?format=json&elements=hotelName,address1,address2,hotelImageUrl,roomImageUrl,reviewCount,reviewAverage,hotelMinCharge,access,roomFacilities,hotelFacilities,aboutMealPlace,breakfastPlace,dinnerPlace,aboutBath,bathType,hotelSpecial&formatVersion=2&searchField=1&responseType=large&keyword=#{encoded_name}&applicationId=#{ENV['id']}"
    uri = URI.parse(rakuten_url)
    response = Net::HTTP.get_response(uri)
    detail = JSON.parse(response.body)

    if detail && detail['hotels'] && detail['hotels'][0] && detail['hotels'][0][0] && detail['hotels'][0][0]['hotelBasicInfo']
      {
        hotel_name: detail['hotels'][0][0]['hotelBasicInfo']['hotelName'],
        address1: detail['hotels'][0][0]['hotelBasicInfo']['address1'],
        address2: detail['hotels'][0][0]['hotelBasicInfo']['address2'],
        hotel_image: detail['hotels'][0][0]['hotelBasicInfo']['hotelImageUrl'],
        room_image: detail['hotels'][0][0]['hotelBasicInfo']['roomImageUrl'],
        review_count: detail['hotels'][0][0]['hotelBasicInfo']['reviewCount'],
        review_average: detail['hotels'][0][0]['hotelBasicInfo']['reviewAverage'],
        access: detail['hotels'][0][0]['hotelBasicInfo']['access'],
        min_charge: detail['hotels'][0][0]['hotelBasicInfo']['hotelMinCharge'],
        hotel_special: detail['hotels'][0][0]['hotelBasicInfo']['hotelSpecial']

      }
    else
      {}
    end
  end

  def fetch_hotel_no(hotel_name)
    encoded_name = URI.encode_www_form_component(hotel_name)
    hotel_no_url = "https://app.rakuten.co.jp/services/api/Travel/KeywordHotelSearch/20170426?format=json&hotelThumbnailSize=1&elements=hotelNo&formatVersion=2&searchField=1&responseType=large&keyword=#{encoded_name}&applicationId=#{ENV['id']}"
    uri = URI.parse(hotel_no_url)
    response = Net::HTTP.get_response(uri)
    detail = JSON.parse(response.body)

    if detail && detail['hotels'] && detail['hotels'][0] && detail['hotels'][0][0] && detail['hotels'][0][0]['hotelBasicInfo']
      detail['hotels'][0][0]['hotelBasicInfo']['hotelNo']
    end
  end

  def check_vacant_rooms(hotel_no, checkin_date, checkout_date, adult_num, infant_with_mb, infant_with_m, infant_with_b,
                         infant_without_mb)
    vacant_url = "https://app.rakuten.co.jp/services/api/Travel/VacantHotelSearch/20170426?format=json&elements=roomName,planName,payment,reserveUrl,stayDate,rakutenCharge,total&checkinDate=#{checkin_date}&checkoutDate=#{checkout_date}&adultNum=#{adult_num}&infantWithMBNum=#{infant_with_mb}&infantWithMNum=#{infant_with_m}&infantWithBNum=#{infant_with_b}&infantWithoutMBNum=#{infant_without_mb}&hotelNo=#{hotel_no}&applicationId=#{ENV['id']}"
    uri = URI.parse(vacant_url)
    response = Net::HTTP.get_response(uri)
    room_info = JSON.parse(response.body)
    @room_info = room_info
    @room_info
  end
end

app/helpers/hotels_helper.rb
# frozen_string_literal: true

module HotelsHelper
end

app/views/hotels/_map.html.erb
<div id="map" style="height: 400px; width: 100%;"></div>
<script>
  let map;
  let infowindow;

  async function initMap() {
    infowindow = new google.maps.InfoWindow();
    map = new google.maps.Map(document.getElementById("map"), {
      zoom: 15
    });


    const geocoder = new google.maps.Geocoder();
    const bounds = new google.maps.LatLngBounds();
    const hotelAddresses = <%= @hotel_apis.map { |hotel| "#{hotel[:address1]}, #{hotel[:address2]}" }.to_json.html_safe %>;

for (let i = 0; i < hotelAddresses.length; i++) {
      const address = hotelAddresses[i];
      await new Promise((resolve, reject) => {
        geocoder.geocode({ 'address': address }, (results, status) => {
          if (status === 'OK' && results) {
            const result = results[0];
            createMarker(result,  <%= @hotel_apis.to_json.html_safe %>[i]); // ホテルのインデックスを渡す
            bounds.extend(result.geometry.location);
            resolve();
          } else {
            reject(new Error('Geocode was not successful for the following reason: ' + status));
          }
        });
      });
    }

  map.fitBounds(bounds);
}

  function createMarker(place,hotelInfo) {
    const marker = new google.maps.Marker({
      map: map,
      position: place.geometry.location
    });

    google.maps.event.addListener(marker, "mouseover", function() {
      infowindow.setContent(`<p>${hotelInfo.hotel_name}</p>`);
      infowindow.open(map, marker);
    });

    google.maps.event.addListener(marker, "click", function() {
    // ウィンドウにホテル名と詳細ボタンを表示
    infowindow.setContent(`<p>${hotelInfo.hotel_name}</p><button id="detailButton">★宿情報を見る</button>`);
    infowindow.open(map, marker);
    // ウィンドウが開いた後に、宿情報ボタンがクリックされたときの処理
    google.maps.event.addListenerOnce(infowindow, 'domready', () => {
    document.getElementById('detailButton').addEventListener('click', () => {
      const card = document.querySelector(`[data-hotel-name="${hotelInfo.hotel_name}"]`);
        if (card) {
          card.classList.add("highlighted-card");
          card.scrollIntoView({ behavior: 'smooth', block: 'start' });
        }
      });
    });
  });
}
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['google_api'] %>&callback=initMap" async defer></script>

app/views/hotels/_review.html.erb
<% hotel_reviews.each do |review| %> 
  <div>
    <span class="material-icons">escalator_warning</span>
    <%= review.review_user %>
      <%= review.review_time %> 
      <a href="<%= review.url%>" class="link link-info" target="_blank">引用元：楽天トラベルお客さまの声</a> 
  </div>
  <div class="text-sm">
  <blockquote> <%= review.review %> </blockquote>
  </div>
<% end %>

app/views/hotels/index.html.erb
<h1 class="text-2xl sm:flex justify-center text-gray">
  <span class="material-icons">search</span>
  宿と口コミを探す
</h1>
<div data-controller="area">
<div class="sm:flex justify-center h-screen">
  <div class="japan_map relative box-border card w-96 bg-base-100 shadow-xl md:card-content grid place-items-center"> 
    <%= image_tag "japan_map.png",size: '546×506', alt: '日本地図', class: 'japan_map'%>
    <div class="area_btn z-10  flex justify-center items-cent border-3 border-black rounded-md p-1 mx-auto font-bold whitespace-nowrap">
    <!-- 北海道・東北 -->
      <div class="absolute top-[25%] left-[65%]">
        <button class="btn btn-outline btn-secondary btn-sm" onclick="my_modal_1.showModal()" data-area="1">北海道・東北</button>
      </div>  
      <dialog id="my_modal_1" class="modal">
        <div class="modal-box" data-area-target="prefList" >
          <div class="grid grid-cols-2 gap-4">
            <button class="btn btn-outline btn-secondary" data-action="click->area#selectPrefecture" data-id="1" >北海道</button>
            <button class="btn btn-outline btn-secondary" data-action="click->area#selectPrefecture"  data-id="2">青森県</button>
            <button class="btn btn-outline btn-secondary" data-action="click->area#selectPrefecture"  data-id="3">岩手県</button>
            <button class="btn btn-outline btn-secondary" data-action="click->area#selectPrefecture"  data-id="4">秋田県</button>
            <button class="btn btn-outline btn-secondary" data-action="click->area#selectPrefecture"  data-id="5">宮城県</button>
            <button class="btn btn-outline btn-secondary" data-action="click->area#selectPrefecture"  data-id="6">山形県</button>
            <button class="btn btn-outline btn-secondary" data-action="click->area#selectPrefecture" data-id="7">福島県</button>
          </div>
          <div class="modal-action">
            <form method="dialog">
              <button class="btn">Close</button>
            </form>
          </div>
      </dialog>
    <!-- 関東 -->
      <div class="absolute top-[55%] left-[65%]">
        <button class="btn btn-outline btn-secondary btn-sm" onclick="my_modal_2.showModal()" data-area="2">関東</button>
      </div>
      <dialog id="my_modal_2" class="modal">
        <div class="modal-box" data-area-target="prefList" >
          <div class="grid grid-cols-2 gap-4">
            <button class="btn btn-outline btn-secondary" data-action="click->area#selectPrefecture" data-id="8">茨城県</button>
            <button class="btn btn-outline btn-secondary" data-action="click->area#selectPrefecture"  data-id="9">栃木県</button>
            <button class="btn btn-outline btn-secondary" data-action="click->area#selectPrefecture" div data-id="10">群馬県</button>
            <button class="btn btn-outline btn-secondary" data-action="click->area#selectPrefecture" div data-id="11">埼玉県</button>
            <button class="btn btn-outline btn-secondary" data-action="click->area#selectPrefecture" div data-id="12">千葉県</button>
            <button class="btn btn-outline btn-secondary" data-action="click->area#selectPrefecture" div data-id="13">東京都</button>
            <button class="btn btn-outline btn-secondary" data-action="click->area#selectPrefecture"  data-id="14">神奈川県</button>
          </div>
          <div class="modal-action">
            <form method="dialog">
              <button class="btn">Close</button>
            </form>
          </div>
      </dialog>
      <!-- 中部 -->
      <div class="absolute top-[35%] left-[45%]">
        <button class="btn btn-outline btn-secondary btn-sm" onclick="my_modal_3.showModal()" data-area="3">中部</button>
      </div>
      <dialog id="my_modal_3" class="modal">
        <div class="modal-box" data-area-target="prefList" >
          <div class="grid grid-cols-2 gap-4">
            <button class="btn btn-outline btn-secondary" data-action="click->area#selectPrefecture" data-id="15">山梨県</button>
            <button class="btn btn-outline btn-secondary" data-action="click->area#selectPrefecture" data-id="16">長野県</button>
            <button class="btn btn-outline btn-secondary" data-action="click->area#selectPrefecture" data-id="17">新潟県</button>
            <button class="btn btn-outline btn-secondary" disabled="disabled" data-action="click->area#selectPrefecture"  data-id="18">富山県</button>
            <button class="btn btn-outline btn-secondary" disabled="disabled" data-action="click->area#selectPrefecture"  data-id="19">石川県</button>
            <button class="btn btn-outline btn-secondary"  disabled="disabled" data-action="click->area#selectPrefecture" data-id="20">福井県</button>
            <button class="btn btn-outline btn-secondary" data-action="click->area#selectPrefecture" data-id="21">静岡県</button>
            <button class="btn btn-outline btn-secondary" disabled="disabled" data-action="click->area#selectPrefecture" data-id="22">愛知県</button>
            <button class="btn btn-outline btn-secondary" disabled="disabled" data-action="click->area#selectPrefecture" data-id="23">岐阜県</button>
          </div>
          <div class="modal-action">
            <form method="dialog">
              <button class="btn">Close</button>
            </form>
          </div>
      </dialog>
      <!-- 近畿 -->
      <div class="absolute top-[65%] left-[40%]">
        <button class="btn btn-outline btn-secondary btn-sm" onclick="my_modal_4.showModal()" data-area="4" data-area="4">近畿</span>
      </div>
      <dialog id="my_modal_4" class="modal">
        <div class="modal-box" data-area-target="prefList" >
          <div class="grid grid-cols-2 gap-4">
            <button class="btn btn-outline btn-secondary"  disabled="disabled" data-action="click->area#selectPrefecture" data-id="24">三重県</button>
            <button class="btn btn-outline btn-secondary" data-action="click->area#selectPrefecture" data-id="25">滋賀県</button>
            <button class="btn btn-outline btn-secondary" data-action="click->area#selectPrefecture" data-id="26">京都府</button>
            <button class="btn btn-outline btn-secondary" data-action="click->area#selectPrefecture" data-id="27">大阪府</button>
            <button class="btn btn-outline btn-secondary" data-action="click->area#selectPrefecture"  data-id="28">兵庫県</button>
            <button class="btn btn-outline btn-secondary" data-action="click->area#selectPrefecture"  data-id="29">奈良県</button>
            <button class="btn btn-outline btn-secondary" data-action="click->area#selectPrefecture"  data-id="30">和歌山県</button>
          </div>
        <div class="modal-action">
          <form method="dialog">
            <button class="btn">Close</button>
          </form>
        </div>
      </dialog>
      <!-- 中国・四国 -->
      <div class="absolute top-[52%] left-[10%]">
        <button class="btn btn-outline btn-secondary btn-sm" onclick="my_modal_5.showModal()" data-area="5">中国・四国</span>
      </div>
      <dialog id="my_modal_5" class="modal">
        <div class="modal-box" data-area-target="prefList" >
          <div class="grid grid-cols-2 gap-4">
            <button class="btn btn-outline btn-secondary" disabled="disabled" data-action="click->area#selectPrefecture"  data-id="31">鳥取県</button>
            <button class="btn btn-outline btn-secondary" disabled="disabled" data-action="click->area#selectPrefecture"  data-id="32">島根県</button>
            <button class="btn btn-outline btn-secondary" disabled="disabled" data-action="click->area#selectPrefecture"  data-id="33">岡山県</button>
            <button class="btn btn-outline btn-secondary" disabled="disabled" data-action="click->area#selectPrefecture"  data-id="34">広島県</button>
            <button class="btn btn-outline btn-secondary" disabled="disabled" data-action="click->area#selectPrefecture"  data-id="35">山口県</button>
            <button class="btn btn-outline btn-secondary" data-action="click->area#selectPrefecture"  data-id="36">香川県</button>
            <button class="btn btn-outline btn-secondary" data-action="click->area#selectPrefecture"  data-id="37">愛媛県</button>
            <button class="btn btn-outline btn-secondary" data-action="click->area#selectPrefecture"  data-id="38">徳島県</button>
            <button class="btn btn-outline btn-secondary" data-action="click->area#selectPrefecture"  data-id="39">高知県</button>
          </div>
          <div class="modal-action">
            <form method="dialog">
              <button class="btn">Close</button>
            </form>
          </div>
      </dialog>
      <!-- 九州・沖縄 -->
      <div class="absolute top-[78%] left-[5%]">
        <button class="btn btn-outline btn-secondary btn-sm" onclick="my_modal_6.showModal()" data-area="6">九州・沖縄</span>
      </div>
      <dialog id="my_modal_6" class="modal">
        <div class="modal-box" data-area-target="prefList" >
          <div class="grid grid-cols-2 gap-4">
            <button class="btn btn-outline btn-secondary" data-action="click->area#selectPrefecture"  data-id="40">福岡県</button>
            <button class="btn btn-outline btn-secondary" data-action="click->area#selectPrefecture"  data-id="41">佐賀県</button>
            <button class="btn btn-outline btn-secondary" data-action="click->area#selectPrefecture"  data-id="42">長崎県</button>
            <button class="btn btn-outline btn-secondary" data-action="click->area#selectPrefecture"  data-id="43">熊本県</button>
            <button class="btn btn-outline btn-secondary" data-action="click->area#selectPrefecture"  data-id="44">大分県</button>
            <button class="btn btn-outline btn-secondary" data-action="click->area#selectPrefecture"  data-id="45">宮崎県</button>
            <button class="btn btn-outline btn-secondary" data-action="click->area#selectPrefecture"  data-id="46">鹿児島県</button>
            <button class="btn btn-outline btn-secondary" disabled="disabled" data-action="click->area#selectPrefecture"  data-id="47">沖縄県</button>
          </div>
          <div class="modal-action">
            <form method="dialog">
              <button class="btn">Close</button>
            </form>
          </div>
      </dialog>
    </div>
  </div>

<div class="grid place-items-start md:place-items-center">
  <%= search_form_for @q, url: search_hotels_path do |f| %>
    <div class="mb-4">
      <%= f.label :prefecture_id_eq, '都道府県', class: "font-medium" %>
      <%= f.collection_select :prefecture_id_eq,  @prefectures, :id, :name, {include_blank: 'すべての都道府県'}, {class: "form-select mt-1 block w-full rounded-md border-gray-300 shadow-sm"} %>
    </div>
    <div class="space-x-2">
      <%= f.label  :reviews_age_eq, '子供の年齢', class: "font-medium" %>
      <div class="flex items-center space-x-2">
        <%= f.radio_button :reviews_age_eq, nil, class: "form-radio"  %><span>指定なし</span>
        <%= f.radio_button :reviews_age_eq, 0, class: "form-radio"  %><span>0歳</span>
        <%= f.radio_button :reviews_age_eq, 1, class: "form-radio"  %><span>1歳</span>
      </div>
    </div>
    <br>
      <%= f.submit '検索', class: "btn btn-secondary text-white" %>
  <% end %>
</div>
</div>
</div>

app/views/hotels/search.html.erb
<br>
<h1 class="text-2xl sm:flex justify-center">
  <span class="material-icons">hotel</span>
  宿泊施設一覧
</h1>
<br>
<div class="item-center h-screen">
  
  <% if @reviews.presence %>
  <%= render 'hotels/map' %>
    <% @reviews.group_by{|review|review.hotel}.each do |hotel, hotel_reviews| %>  
        <% hotel_api = @hotel_apis.find { |api| api[:hotel_name].start_with?(hotel.name) } %>
        <% if hotel_api %>
        <div class="card bg-base-100 shadow-xl border border-gray-200" data-hotel-name="<%= hotel.name %>">
        <div class="card-body">
            <h2 class="card-title"><%= hotel.name %></h2>    
            <div class="card-actions justify-end">
              <a href="<%= hotel_path(hotel) %>" class="btn btn-secondary text-white">詳細</a>
            </div>
              <%= hotel_api[:hotel_special] %>
              <div>
                <span class="material-icons">location_on</span>
                <%= hotel_api[:address1] %><%= hotel_api[:address2]%>
              </div>
              <img src="<%= hotel_api[:hotel_image] %>" class="max-w-xs">
              <div class=text-xs>© RakutenTravel</div>
              <div class="rating rating-sm">
                <span class="material-icons">reviews</span>
                平均 <%= hotel_api[:review_average] %>
                  <% 5.times do |i| %>
                    <% if i < hotel_api[:review_average].to_i %>
                      <svg class="h-5 w-5 text-orange-400" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.37 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.176 0l-2.8 2.034c-.785.57-1.84-.197-1.54-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.049 8.719c-.782-.57-.38-1.81.588-1.81h3.462a1 1 0 00.95-.69l1.07-3.292z"/></svg>
                    <% else %>
                      <svg class="h-5 w-5 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.37 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.176 0l-2.8 2.034c-.785.57-1.84-.197-1.54-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.049 8.719c-.782-.57-.38-1.81.588-1.81h3.462a1 1 0 00.95-.69l1.07-3.292z"/></svg>
                    <% end %>
                  <% end %>
                【口コミ数 全<%= hotel_api[:review_count] %>件】
              </div>
          <%= render partial:'hotels/review', locals: { hotel_reviews: hotel_reviews } %>
        </div> 
      </div>
      <%end%>
    <%end%>
  <% else %>
    該当する宿はありません
      <a href= "<%=root_path%>" class="btn btn-neutral">トップページへ戻る</a>
  <% end %>
  <br>
</div>